environment:
  nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      Install-Product node $env:nodejs_version
      npm install --loglevel=error

      "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII
test_script:
  - node --version
  - npm --version
  - npm run test
after_deploy:
  - ps: npm publish
    on:
      branch: master